### ISSUE TITLE
Would you like to share other distilled datasets ?

### ISSUE THREAD

**Issue by chynphh** [chenyangh/DSLP#3]
Hi all. 
Thanks for your nice code!
Would you like to share other distilled datasets ?

**Comment by chenyangh** [comment]
Hi,

I may release all the distilled data soon.

**Comment by chenyangh** [comment]
Hi, all the binarized files are [here](https://drive.google.com/file/d/1MUNYkH5Cf2LC6Zv1Q01VorbNQlrLYOPk/view?usp=sharing).

**Comment by chynphh** [comment]
thanks!!!
