### ISSUE TITLE
Does your implementation for CTC + GLAT work?

### ISSUE THREAD

**Issue by SirRob1997** [chenyangh/DSLP#5]
I've looked through the code for `nat_ctc_glat.py` and was wondering how the alignment works for the glancing sampling. For the normal CTC without GLAT this is handled by `F.ctc_loss` but it seems it's not so straightforward for the GLAT part. I tried to code it up following some of the implementation here as well as in the GLAT repository.

For me, it fails for this check `pred_tokens == tgt_tokens` in the GLAT part. Which makes sense as the `pred_tokens` will have the length of the upsampled source from CTC but the `tgt_tokens` are most likely smaller. 

Not sure if it fails using your exact code as well but it would make sense to me, what did you change to make this work?

**Comment by chenyangh** [comment]
Hi, 

Actually, this ctc+glat model was not finished, and I should probably delete it. 

According to Gu and Kong (2021), we can treat the most probable CTC alignment as the target. I actually have this part implemented in the `CTC with DSLP & Mixed Training` model. You can find it here: https://github.com/chenyangh/DSLP/blob/a803b46ffc7aaf4b4117a9bade83b106237446e7/fairseq/models/nat/nat_ctc_sd_ss.py#L384

Then you can replace that in the normal GLAT training.

**Comment by SirRob1997** [comment]
Ahhh, I see. To verify: so `oracle` will be the tensor used as `tgt_tokens`?

**Comment by chenyangh** [comment]
Yes,  `oracle` is the token ID of best alignment. `best_align` itself is only the positions.

**Comment by SirRob1997** [comment]
Why is `// 2` needed in above code?

**Comment by chenyangh** [comment]
The algorithm is implemented by the imputer paper: https://github.com/rosinality/imputer-pytorch

**Comment by SirRob1997** [comment]
Thanks so much for the quick responses, this was really helpful! One last question: What is the point of the `--no-empty` flag or rather the masks that are used here:

https://github.com/chenyangh/DSLP/blob/a803b46ffc7aaf4b4117a9bade83b106237446e7/fairseq/models/nat/nat_ctc_sd_ss.py#L389

**Comment by chenyangh** [comment]
It is a good question, Robin. 

The `//2` operation essentially put the empty tokens to the intermediate `argmax` sequence.  Since we know that the empty tokens are not informative, we tried to not perform this option (although it is slightly different from the math). 

In our experiments, it may have some small benefits, but not very consistent. Therefore we choose not to include this trick for simplicity.
